name: Slack Recaps

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Run mode"
        type: choice
        options: [DRYRUN, DAILY, WEEKLY]
        default: DRYRUN
      post_to_channel_id:
        description: "Override channel ID to post into (e.g., C0123ABCDEF) — optional"
        required: false
        type: string
  schedule:
    # Fire around the local 5pm boundary in Denver for both DST/Standard time.
    - cron: "0 23 * * *"   # 5pm during MDT
    - cron: "0 0 * * *"    # 5pm during MST

concurrency:
  group: slack-recaps
  cancel-in-progress: false

jobs:
  recap:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      # Decide mode automatically for scheduled runs (Mon=weekly, else=daily)
      - name: Decide MODE for scheduled runs
        if: ${{ github.event_name == 'schedule' }}
        run: |
          DOW=$(TZ=America/Denver date +%u)   # 1=Mon ... 5=Fri ... 7=Sun
          if [ "$DOW" = "5" ]; then
            echo "MODE=WEEKLY" >> $GITHUB_ENV   # Fridays → weekly
          else
            echo "MODE=DAILY" >> $GITHUB_ENV    # all other days → daily
          fi
    

      # For manual runs, use the chosen input
      - name: Set MODE for manual runs
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo "MODE=${{ inputs.mode }}" >> $GITHUB_ENV

      # Only proceed when it's exactly 5pm local (skips the non-5pm cron)
      - name: Gate to 5pm America/Denver
        if: ${{ github.event_name == 'schedule' }}
        run: |
          HOUR=$(TZ=America/Denver date +%H)
          if [ "$HOUR" = "17" ]; then
            echo "RUN_RECAP=1" >> $GITHUB_ENV
          else
            echo "Not 5pm local — skipping."
          fi

      - name: Debug
        run: |
          echo "MODE=$MODE"
          echo "CHANNEL_ID length: ${#CHANNEL_ID}"
          if [ -n "${{ inputs.post_to_channel_id }}" ]; then
            echo "Manual override: will post to inputs.post_to_channel_id"
          elif [ -n "$POST_TO_CHANNEL_ID" ]; then
            echo "Will post to POST_TO_CHANNEL_ID secret"
          else
            echo "No override set: will post to CHANNEL_ID"
          fi
        env:
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          POST_TO_CHANNEL_ID: ${{ secrets.POST_TO_CHANNEL_ID }}

      - name: Run recap bot
        # Manual runs always allowed; scheduled runs only when it's 5pm local.
        if: ${{ github.event_name == 'workflow_dispatch' || env.RUN_RECAP == '1' }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          # If provided via manual input, use that; else fall back to secret (can be empty).
          POST_TO_CHANNEL_ID: ${{ inputs.post_to_channel_id != '' && inputs.post_to_channel_id || secrets.POST_TO_CHANNEL_ID }}
          MODE: ${{ env.MODE }}
          TZ_NAME: America/Denver
        run: python recap_bot.py
