name: Slack Recaps

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Run mode"
        type: choice
        options: [DRYRUN, DAILY, WEEKLY]
        default: DRYRUN
      post_to_channel_id:
        description: "Override channel ID to post into (e.g., C0123ABCDEF) — optional"
        required: false
        type: string
  schedule:
    # 9:00 AM America/Denver (MDT/MST) for DAILY (yesterday)
    - cron: "0 15 * * *"   # 9am during MDT (UTC-6)
    - cron: "0 16 * * *"   # 9am during MST (UTC-7)
    # 2:00 PM America/Denver (MDT/MST) for WEEKLY (Fridays)
    - cron: "0 20 * * 5"   # 2pm Friday during MDT (UTC-6)
    - cron: "0 21 * * 5"   # 2pm Friday during MST (UTC-7)

concurrency:
  group: slack-recaps
  cancel-in-progress: false

jobs:
  recap:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      # Decide whether to run and which MODE, based on local time/day.
      - name: Decide MODE & gate by local time
        if: ${{ github.event_name == 'schedule' }}
        run: |
          LOCAL_HOUR=$(TZ=America/Denver date +%H)
          DOW=$(TZ=America/Denver date +%u)   # 1=Mon ... 5=Fri ... 7=Sun
          echo "Local hour: $LOCAL_HOUR  DOW: $DOW"
          # 9am local → DAILY (yesterday)
          if [ "$LOCAL_HOUR" = "09" ]; then
            echo "MODE=DAILY" >> $GITHUB_ENV
            echo "RUN_RECAP=1" >> $GITHUB_ENV
            exit 0
          fi
          # 2pm Friday local → WEEKLY
          if [ "$LOCAL_HOUR" = "14" ] && [ "$DOW" = "5" ]; then
            echo "MODE=WEEKLY" >> $GITHUB_ENV
            echo "RUN_RECAP=1" >> $GITHUB_ENV
            exit 0
          fi
          echo "Not a scheduled recap slot — skipping."

      - name: Set MODE for manual runs
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo "MODE=${{ inputs.mode }}" >> $GITHUB_ENV

      - name: Debug
        run: |
          echo "MODE=$MODE"
          echo "CHANNEL_ID length: ${#CHANNEL_ID}"
          echo "Local time: $(TZ=America/Denver date -Is)"
          echo "UTC time:   $(date -u -Is)"
          if [ -n "${{ inputs.post_to_channel_id }}" ]; then
            echo "Manual override: will post to inputs.post_to_channel_id"
          elif [ -n "$POST_TO_CHANNEL_ID" ]; then
            echo "Will post to POST_TO_CHANNEL_ID secret"
          else
            echo "No override set: will post to CHANNEL_ID"
          fi
        env:
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          POST_TO_CHANNEL_ID: ${{ secrets.POST_TO_CHANNEL_ID }}

      - name: Run recap bot
        if: ${{ github.event_name == 'workflow_dispatch' || env.RUN_RECAP == '1' }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          POST_TO_CHANNEL_ID: ${{ inputs.post_to_channel_id != '' && inputs.post_to_channel_id || secrets.POST_TO_CHANNEL_ID }}
          MODE: ${{ env.MODE }}
          TZ_NAME: America/Denver
        run: python recap_bot.py
