name: Slack Recaps

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Run mode"
        type: choice
        options: [DRYRUN, DAILY, WEEKLY]
        default: DRYRUN
      post_to_channel_id:
        description: "Override channel ID to post into (e.g., C0123ABCDEF) — optional"
        required: false
        type: string
  schedule:
    # DAILY: run at 08:30 America/Denver to schedule delivery for 09:00
    - cron: "30 14 * * *"   # 08:30 during MDT (UTC-6)
    - cron: "30 15 * * *"   # 08:30 during MST (UTC-7)
    # WEEKLY (Friday): run at 13:30 America/Denver to schedule delivery for 14:00
    - cron: "30 19 * * 5"   # 13:30 Fri during MDT
    - cron: "30 20 * * 5"   # 13:30 Fri during MST

concurrency:
  group: slack-recaps
  cancel-in-progress: false

jobs:
  recap:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      # Decide whether to run and what MODE + target delivery time to use.
      - name: Decide MODE & set schedule target
        if: ${{ github.event_name == 'schedule' }}
        run: |
          H=$(TZ=America/Denver date +%H)
          DOW=$(TZ=America/Denver date +%u)  # 5=Fri
          echo "Local hour: $H  DOW: $DOW"
          if [ "$H" = "08" ]; then
            echo "MODE=DAILY" >> $GITHUB_ENV
            echo "SCHEDULE_AT_LOCAL=09:00" >> $GITHUB_ENV
            echo "RUN_RECAP=1" >> $GITHUB_ENV
            exit 0
          fi
          if [ "$H" = "13" ] && [ "$DOW" = "5" ]; then
            echo "MODE=WEEKLY" >> $GITHUB_ENV
            echo "SCHEDULE_AT_LOCAL=14:00" >> $GITHUB_ENV
            echo "RUN_RECAP=1" >> $GITHUB_ENV
            exit 0
          fi
          echo "Not a recap slot — skipping."

      - name: Set MODE for manual runs
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo "MODE=${{ inputs.mode }}" >> $GITHUB_ENV

      - name: Debug
        run: |
          echo "MODE=$MODE"
          echo "CHANNEL_ID length: ${#CHANNEL_ID}"
          echo "Local time: $(TZ=America/Denver date -Is)"
          echo "UTC time:   $(date -u -Is)"
          if [ -n "${{ inputs.post_to_channel_id }}" ]; then
            echo "Manual override: will post to inputs.post_to_channel_id"
          elif [ -n "$POST_TO_CHANNEL_ID" ]; then
            echo "Will post to POST_TO_CHANNEL_ID secret"
          else
            echo "No override set: will post to CHANNEL_ID"
          fi
        env:
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          POST_TO_CHANNEL_ID: ${{ secrets.POST_TO_CHANNEL_ID }}

      - name: Run recap bot
        if: ${{ github.event_name == 'workflow_dispatch' || env.RUN_RECAP == '1' }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          POST_TO_CHANNEL_ID: ${{ inputs.post_to_channel_id != '' && inputs.post_to_channel_id || secrets.POST_TO_CHANNEL_ID }}
          MODE: ${{ env.MODE }}
          TZ_NAME: America/Denver
          SCHEDULE_AT_LOCAL: ${{ env.SCHEDULE_AT_LOCAL }}
        run: python recap_bot.py
